-- MySQL Script generated by MySQL Workbench
-- 03/30/17 17:24:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema teuremedio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teuremedio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teuremedio` DEFAULT CHARACTER SET utf8 ;
USE `teuremedio` ;

-- -----------------------------------------------------
-- Table `teuremedio`.`tblCategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teuremedio`.`tblCategorias` (
  `idtblCategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `tblCategoriasNome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtblCategorias`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teuremedio`.`tblClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teuremedio`.`tblClientes` (
  `idtblClientes` INT(11) NOT NULL AUTO_INCREMENT,
  `tblClientesNome` VARCHAR(100) NULL DEFAULT NULL,
  `tblClientesCnpj` VARCHAR(11) NULL DEFAULT NULL,
  `tblClientesRazao` VARCHAR(45) NULL DEFAULT NULL,
  `tblClientesEndereco` VARCHAR(45) NULL DEFAULT NULL,
  `tblClientesComplemento` VARCHAR(45) NULL DEFAULT NULL,
  `tblClientesCep` VARCHAR(9) NULL DEFAULT NULL,
  `tblClientesTelefone` VARCHAR(13) NULL DEFAULT NULL,
  `tblClientesWeb` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtblClientes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teuremedio`.`tblProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teuremedio`.`tblProdutos` (
  `idtblProdutos` INT(11) NOT NULL AUTO_INCREMENT,
  `tblProdutosNome` VARCHAR(100) NULL DEFAULT NULL,
  `tblProdutosLaboratorio` VARCHAR(45) NULL DEFAULT NULL,
  `tblCategorias_idtblCategorias` INT(11) NOT NULL,
  `tblClientes_idtblClientes` INT(11) NOT NULL,
  PRIMARY KEY (`idtblProdutos`),
  INDEX `fk_tblProdutos_tblCategorias_idx` (`tblCategorias_idtblCategorias` ASC),
  INDEX `fk_tblProdutos_tblClientes1_idx` (`tblClientes_idtblClientes` ASC),
  CONSTRAINT `fk_tblProdutos_tblCategorias`
    FOREIGN KEY (`tblCategorias_idtblCategorias`)
    REFERENCES `teuremedio`.`tblCategorias` (`idtblCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblProdutos_tblClientes1`
    FOREIGN KEY (`tblClientes_idtblClientes`)
    REFERENCES `teuremedio`.`tblClientes` (`idtblClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teuremedio`.`tblUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teuremedio`.`tblUsuarios` (
  `idtblUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `tblUsuariosNome` VARCHAR(100) NULL DEFAULT NULL,
  `tblUsuariosEmail` VARCHAR(45) NULL DEFAULT NULL,
  `tblUsuariosSenha` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`idtblUsuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
